services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: example
      POSTGRES_DB: exampledb
  backend:
    build: ./Attendance-Backend-with-Go
    ports:
      - "8080:8080"
    depends_on:
      - db