services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: example
      POSTGRES_DB: exampledb
  go-lang:
     build: .
     ports: "8080"
  backend:
    build: ./Attendance-Backend-with-Go
    ports:
      - "3000:3000"
    depends_on:
      - db